export const TRANSPARENT = '.';

export const PALETTE = Object.freeze({
  '.': null,
  k: '#050505',
  s: '#f3d6b0',
  w: '#f0f0f0',
  r: '#b24040',
  b: '#4f6dff',
  h: '#20160d',
  g: '#2b2b2b',
});

function mirrorRows(rows) {
  return rows.map((row) => row.split('').reverse().join(''));
}

const BASE_PLAYER = Object.freeze({
  idle: [
    '....kk....',
    '...kssk...',
    '...kssk...',
    '....hh....',
    '...wwww...',
    '..wwwwww..',
    '..wwwwww..',
    '...w..w...',
    '..ww..ww..',
    '..ww..ww..',
    '..ww..ww..',
    '.ww....ww.',
    '.ww....ww.',
    '..w....w..',
    '..w....w..',
    '.ww....ww.',
  ],
  walk1: [
    '....kk....',
    '...kssk...',
    '...kssk...',
    '....hh....',
    '...wwww...',
    '..wwwwww..',
    '..wwwwww..',
    '...w..w...',
    '..ww..ww..',
    '..ww..ww..',
    '...w..ww..',
    '..ww...ww.',
    '.ww.....w.',
    '.ww....ww.',
    '..w....w..',
    '.ww....w..',
  ],
  walk2: [
    '....kk....',
    '...kssk...',
    '...kssk...',
    '....hh....',
    '...wwww...',
    '..wwwwww..',
    '..wwwwww..',
    '...w..w...',
    '..ww..ww..',
    '..ww..ww..',
    '..ww..w...',
    '.ww...ww..',
    '.w.....ww.',
    '.ww....ww.',
    '..w....w..',
    '..w....ww.',
  ],
  punch: [
    '....kk....',
    '...kssk...',
    '...kssk...',
    '....hh....',
    '...wwwww..',
    '..wwwwwwww',
    '..wwwwwwww',
    '...w..w...',
    '..ww..ww..',
    '..ww..ww..',
    '..ww..ww..',
    '.ww....ww.',
    '.ww....ww.',
    '..w....w..',
    '..w....w..',
    '.ww....ww.',
  ],
  kick: [
    '....kk....',
    '...kssk...',
    '...kssk...',
    '....hh....',
    '...wwww...',
    '..wwwwww..',
    '..wwwwww..',
    '...w..w...',
    '..ww..wwww',
    '..ww..wwww',
    '..ww..ww..',
    '.ww....w..',
    '.ww....ww.',
    '..w....w..',
    '.ww....ww.',
    '.w......w.',
  ],
  hurt: [
    '....kk....',
    '...kssk...',
    '...kssk...',
    '....hh....',
    '..wwww....',
    '.wwwwww...',
    '.wwwwww...',
    '..w..w....',
    '.ww..ww...',
    '.ww..ww...',
    '.ww..ww...',
    'ww....ww..',
    'ww....ww..',
    '.w....w...',
    '.w....w...',
    'ww....ww..',
  ],
  victory: [
    '....kk....',
    '...kssk...',
    '...kssk...',
    '....hh....',
    '..wwwwww..',
    '.wwwwwwww.',
    '.wwwwwwww.',
    '..ww..ww..',
    '.www..www.',
    '.ww....ww.',
    '.ww....ww.',
    '.ww....ww.',
    '.ww....ww.',
    '..w....w..',
    '..w....w..',
    '.ww....ww.',
  ],
  death: [
    '..........',
    '..........',
    '..........',
    '..kkkk....',
    '.ksskkk...',
    '.ksskkk...',
    '..hhhh....',
    '.wwwwww...',
    'wwwwwwww..',
    'wwwwwwww..',
    '..ww..ww..',
    '...ww..ww.',
    '..ww...ww.',
    '.ww.....w.',
    '.ww....ww.',
    '..wwwwww..',
  ],
});

function makeFrame(name, rows) {
  return Object.freeze({ name, width: rows[0].length, height: rows.length, rows: Object.freeze(rows) });
}

const PLAYER_FRAMES = Object.freeze(
  Object.fromEntries(Object.entries(BASE_PLAYER).map(([name, rows]) => [name, makeFrame(name, rows)])),
);

const ENEMY_FRAMES = Object.freeze(
  Object.fromEntries(
    Object.entries(BASE_PLAYER).map(([name, rows]) => [name, makeFrame(name, mirrorRows(rows))]),
  ),
);

export const ACTOR_SPRITES = Object.freeze({
  player: PLAYER_FRAMES,
  enemy: ENEMY_FRAMES,
});
